import {Ad} from './ad.model';
import {Rating} from './rating.model';
import {Application} from './application.model';
export class User {
    id: number;
    ads: Array<Ad>;
    authorities:Array<string>;
    employeeRatings:Array<Rating>;
    employerRatings:Array<Rating>;
    ratedEmployees:Array<Rating>;
    ratedEmployers:Array<Rating>;
    applications:Application;
    sentMessages = [];
    receivedMessages = [];
    employerRatingScore: number;
    employeeRatingScore: number;
    email: string;
    phone: string;
    userName: string;
    password: string;
    fullName: string;
    type: string;
    postalCode: string;
    city: string;
    address: string;
    balance: number;
    reported: number;
    blocked: boolean;
    ableToAd: boolean;
    enabled: boolean;
    verificated: boolean;
}
